[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/generate-notes"
  to = "/.netlify/functions/api/generate-notes"
  status = 200

[[redirects]]
  from = "/generate-quiz"
  to = "/.netlify/functions/api/generate-quiz"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
